# Generated by Django 4.1.5 on 2023-01-12 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flour_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flour_type', models.CharField(max_length=50)),
                ('cups', models.IntegerField()),
                ('grams', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('flour_amount', models.IntegerField()),
                ('salt_amount', models.IntegerField()),
                ('yeast_amount', models.IntegerField()),
                ('water', models.IntegerField()),
                ('directions', models.CharField(max_length=400)),
                ('image', models.CharField(max_length=400)),
                ('public', models.BooleanField()),
                ('flour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagelapi.flour_type')),
            ],
        ),
        migrations.CreateModel(
            name='Salt_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt_type', models.CharField(max_length=50)),
                ('teaspoons', models.IntegerField()),
                ('grams', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=400)),
                ('uid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Yeast_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yeast_type', models.CharField(max_length=50)),
                ('ounces', models.IntegerField()),
                ('grams', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagelapi.category')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagelapi.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='salt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagelapi.salt_type'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagelapi.user'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='yeast_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagelapi.yeast_type'),
        ),
    ]
