# Generated by Django 4.1.5 on 2023-01-14 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagelapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='flour_id',
            new_name='flour',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='salt_id',
            new_name='salt',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='yeast_id',
            new_name='yeast',
        ),
    ]
